export const NEW = 'NEW'
export const SAVE = 'SAVE'
export const SUBMIT = 'SUBMIT'
export const LOAD = 'LOAD'
export const LOAD_CONFIG = 'LOAD_CONFIG'
export const DESERIALIZE = 'DESERIALIZE'
export const RELOAD_DATASET = 'RELOAD_DATASET'
