FROM node:10-slim

RUN npm install --global npm@6.2.0
RUN npm -v

ENV HOST 0.0.0.0

ENV APP_DIR /app

VOLUME $APP_DIR
WORKDIR /


EXPOSE 3000

COPY entrypoint.web.sh /entrypoint.web.sh
RUN chmod 755 /entrypoint.web.sh


ENTRYPOINT [ "/entrypoint.web.sh"]
CMD ["dev" , "install"]
