FROM node:10-stretch

RUN npm install --global npm@6.5.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app/
RUN node -v && npm ci

ENV BUILDING_WITHOUT_PG_ACCESS=yes

# Build app
RUN npm run build

ENV BUILDING_WITHOUT_PG_ACCESS=

ENV HOST 0.0.0.0
EXPOSE 3000

# entrypoint
RUN cp docker-app-prod/entrypoint.web.sh /usr/src/app/entrypoint.web.sh
RUN chmod 755 /usr/src/app/entrypoint.web.sh

ENTRYPOINT [ "/usr/src/app/entrypoint.web.sh"]
