FROM node:10-slim
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

RUN npm install -g postgraphile@4.0.1

COPY entrypoint.postgraphile.sh /entrypoint.postgraphile.sh
RUN chmod 755 /entrypoint.postgraphile.sh

EXPOSE 5000

ENTRYPOINT [ "/entrypoint.postgraphile.sh"]
