query ActivityLog {
  logs: allLogs (first: 15, orderBy: EVENT_DATE_DESC) {
    lines: nodes {
      id,
      author: personByAuthorId {
        id,
        name,
        avatar
      },
      thread: threadByThreadId {
        id,
        iri,
        headline
      }
      actionType,
      eventDate
    }
  }
}
