query GetAllDiscussions ($threadType: ThreadType!, $orderBy: [ThreadsOrderBy!]) {
  discussions: allThreads (condition: {threadType: $threadType, isDraft: false}, orderBy: $orderBy) {
    nodes {
      id,
      headline,
      body,
      hat: hatByHatId {
        title
      },
      author: personByAuthorId {
        name
      },
      iri,
      createdAt,
      updatedAt,
      threadType,
      authorId,
      externalId,
      status,
      proposalObject,
      votesByThreadId {
        votes: nodes {
          vote
        }
      }
    }
  }
}
