query AdminHatList {
  allHats (orderBy: TITLE_ASC) {
    hats: nodes {
      id,
      title,
      description,
      holders: hatPeopleByHatId {
        persons: nodes {
          person: personByPersonId {
            id,
            name
          }
        }
      }
    }
  }
}
