query GetAllDiscussions ($first: Int!, $offset: Int!, $orderBy: [ThreadsOrderBy!]) {
  discussions: allThreads (condition: {threadType: PROPOSAL, isDraft: false}, orderBy: $orderBy, first: $first, offset: $offset) {
    nodes {
      id,
      headline,
      body,
      hat: hatByHatId {
        id,
        title
      },
      author: personByAuthorId {
        id,
        name
      },
      iri,
      createdAt,
      updatedAt,
      threadType,
      authorId,
      externalId,
      status,
      proposalObject,
      votesByThreadId {
        votes: nodes {
          vote
        }
      }
    }
  }
}
