query ProposalsByIri ($iri: String!) {
  changedPropertyProposals: allThreads (condition: {iri: $iri, isEdit: true, threadType: PROPOSAL, status: OPEN, isDraft: false}) {
    proposals: nodes {
      id,
      headline,
      body,
      hat: hatByHatId {
        id,
        title
      },
      author: personByAuthorId {
        id,
        avatar,
        name
      },
      iri,
      threadType,
      authorId,
      externalId,
      proposalObject,
      isEdit,
      updatedAt
    }
  }
}
