query CountProposals {
  proposals: allThreads (condition: {threadType: PROPOSAL, status: OPEN, isDraft: false}) {
    proposals: nodes {
      id,
      iri,
      isEdit,
      originalIri,
      proposalObject
    }
  }
}
