query GetDiscussion ($id: Int!) {
  discussion: threadById (id: $id) {
    id,
    headline,
    body,
    hat: hatByHatId {
      title
    },
    author: personByAuthorId {
      avatar,
      name
    },
    iri,
    threadType,
    authorId,
    createdAt,
    proposalObject,
    answers: messagesByThreadId {
      messages: nodes {
        id,
        body,
        createdAt,
        author: personByAuthorId {
          name,
          avatar
        }
      }
    }
  }
}
