query DiscussionsByIri ($iri: String!) {
  discussions: allThreads (condition: {iri: $iri, threadType: DISCUSSION, status: OPEN}) {
    discussions: nodes {
      id,
      headline,
      body,
      author: personByAuthorId {
        id,
        avatar,
        name
      },
      createdAt,
      answers: messagesByThreadId {
        messages: nodes {
          id
        }
      }
    }
  }
}
