query GetDiscussion ($id: Int!) {
  discussion: threadById (id: $id) {
    id,
    headline,
    body,
    hat: hatByHatId {
      id,
      title
    },
    author: personByAuthorId {
      id,
      name,
      avatar,
      holding: hatPeopleByPersonId {
        hats: nodes {
          hat: hatByHatId {
            id,
            title
          }
        }
      }
    },
    iri,
    threadType,
    authorId,
    createdAt,
    proposalObject,
    answers: messagesByThreadId {
      messages: nodes {
        id,
        body,
        createdAt,
        author: personByAuthorId {
          id,
          name,
          avatar,
          holding: hatPeopleByPersonId {
            hats: nodes {
              hat: hatByHatId {
                id,
                title
              }
            }
          }
        },
        hat: hatByHatId {
          id,
          title
        }
      }
    }
  }
}
