query PrivateConfigVersion ($version: Int!) {
  privateConfigVersion(version: $version) {
    createdAt
    id
    reason
    forge
    editor
    ontology
    smtp
    personByAuthorId {
      avatar
      username
    }
  }
}
