query GetUserContent ($iri: String!) {
  proposals: allThreads (condition: {iri: $iri, threadType: PROPOSAL, status: OPEN, isDraft: false}) {
    proposals: nodes {
      id,
      headline,
      body,
      hat: hatByHatId {
        title
      },
      author: personByAuthorId {
        avatar,
        name
      },
      iri,
      threadType,
      authorId,
      externalId,
      proposalObject
    }
  }
}
