query UserDrafts ($authorId: Int!) {
  proposals: allThreads (condition: {authorId: $authorId, threadType: PROPOSAL, isDraft: true}) {
    drafts: nodes {
      id,
      headline,
      iri,
      updatedAt,
      proposalObject
    }
  }
}
