query GetUserContent ($authorId: Int!) {
  proposals: allThreads (condition: {authorId: $authorId, threadType: PROPOSAL, isDraft: true, status: OPEN}) {
    drafts: nodes {
      nodeId,
      id,
      headline,
      iri,
      updatedAt,
      proposalObject
    }
  }
}
